# Generated by Django 5.2.6 on 2025-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_shopuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
