# Generated by Django 5.2.6 on 2025-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_shopuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
