# Generated by Django 5.2.8 on 2025-11-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features_products',
        ),
    ]
