# Generated by Django 5.2.8 on 2025-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='کد تخفیف')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='shop_discou_created_abb056_idx')],
            },
        ),
    ]
