# Generated by Django 5.2.8 on 2025-11-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
