# Generated by Django 5.2.8 on 2025-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
