# Generated by Django 5.2.6 on 2025-11-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oreder_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
