# Generated by Django 5.2.8 on 2025-11-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_transaction_updated_alter_transaction_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oreder_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=100),
        ),
    ]
